// react-app/src/components/todoApp/Footer.tsx
import { useMemo } from 'react'
import { Link } from 'react-router-dom'
import { useFilter } from '~/hooks/useFilter'
import { useTodos } from '~/hooks/useTodos'

export const Footer = () => {
  const {
    links
  } = useFilter()
  const {
    activeTodosCount,
    clearCompletedTodos,
    completedTodosCount,
    totalTodosCount
  } = useTodos()

  return useMemo(() => (
    <footer
      className="footer"
      style={{
        display: totalTodosCount ? 'block' : 'none'
      }}
    >
      <span className="todo-count">
        <strong>{activeTodosCount}</strong> items left
      </span>
      <ul className="filters">
        {
          links.map((link, index) => (
            <li key={index}>
              <Link
                className={link.selected ? 'selected' : ''}
                to={link.to}
              >{link.label}</Link>
            </li>
          ))
        }
      </ul>
      <button
        className="clear-completed"
        onClick={clearCompletedTodos}
        style={{
          display: completedTodosCount ? 'block' : 'none'
        }}
      >
        Clear completed
      </button>
    </footer>
  ), [
    activeTodosCount,
    completedTodosCount,
    links,
    totalTodosCount
  ])
}

// vue-app/src/components/todoApp/Footer.tsx
import {
  defineComponent
} from 'vue'
import { RouterLink as Link } from 'vue-router'
import { useFilter } from '~/composables/useFilter'
import { useTodos } from '~/composables/useTodos'

export const Footer = defineComponent(() => {
  const {
    links
  } = useFilter()
  const {
    activeTodosCount,
    clearCompletedTodos,
    completedTodosCount,
    totalTodosCount
  } = useTodos()

  return () => (
    <footer
      class="footer"
      style={{
        display: totalTodosCount.value ? 'block' : 'none'
      }}
    >
      <span class="todo-count">
        <strong>{activeTodosCount.value}</strong> items left
      </span>
      <ul class="filters">
        {
          links.value.map((link, index) => (
            <li key={index}>
              <Link
                class={link.selected ? 'selected' : ''}
                to={link.to}
              >{link.label}</Link>
            </li>
          ))
        }
      </ul>
      <button
        class="clear-completed"
        onClick={clearCompletedTodos}
        style={{
          display: completedTodosCount.value ? 'block' : 'none'
        }}
      >
        Clear completed
      </button>
    </footer>
  )
})
