// react-app/src/components/todoApp/List.tsx
import { useMemo } from 'react'
import { ListItem } from '~/components/todoApp/ListItem'
import { useTodos } from '~/hooks/useTodos'
import { useFilter } from '~/hooks/useFilter'

export const List = () => {
  const {
    currentFilter,
    filterTodos
  } = useFilter()
  const {
    todos
  } = useTodos()

  const filtered = useMemo(
    () => filterTodos(todos),
    [
      currentFilter,
      todos
    ]
  )

  return (
    <ul className="todo-list">
      {
        filtered.map(item => (
          <ListItem
            key={item.id}
            todo={item}
          />
        ))
      }
    </ul>
  )
}

// vue-app/src/components/todoApp/List.tsx
import {
  computed,
  defineComponent
} from 'vue'
import { ListItem } from '~/components/todoApp/ListItem'
import { useTodos } from '~/composables/useTodos'
import { useFilter } from '~/composables/useFilter'

export const List = defineComponent(() => {
  const {
    filterTodos
  } = useFilter()
  const {
    todos
  } = useTodos()

  const filtered = computed(
    () => filterTodos(todos?.value ?? [])
  )

  return () => (
    <ul class="todo-list">
      {
        filtered.value.map(item => (
          <ListItem
            key={item.id}
            todo={item}
          />
        ))
      }
    </ul>
  )
})
