// vue-app/src/components/todoApp/Header.tsx
import {
  defineComponent,
  ref
} from 'vue'
import { useTodos } from '~/composables/useTodos'

export const Header = defineComponent(() => {
  const textRef = ref<HTMLInputElement>()
  const {
    addTodo
  } = useTodos()

  const handleKeyDown = (event: KeyboardEvent) => {
    if (event.key !== 'Enter') {
      return
    }

    event.preventDefault()

    const current = textRef.value

    if (current?.value) {
      addTodo(current.value)

      current.value = ''
    }
  }

  return () => (
    <header class="header">
      <h1>todos</h1>
      <input
        autofocus
        class="new-todo"
        onKeydown={handleKeyDown}
        placeholder="What needs to be done?"
        ref={textRef}
      />
    </header>
  )
})

// react-app/src/components/todoApp/Header.tsx
import {
  useMemo,
  useRef,
  type KeyboardEventHandler
} from 'react'
import { useTodos } from '~/hooks/useTodos'

export const Header = () => {
  const textRef = useRef<HTMLInputElement>(null)
  const {
    addTodo
  } = useTodos()

  const handleKeyDown: KeyboardEventHandler<HTMLInputElement> = (event) => {
    if (event.key !== 'Enter') {
      return
    }

    event.preventDefault()

    const current = textRef.current

    if (current?.value) {
      addTodo(current.value)

      current.value = ''
    }
  }

  return useMemo(() => (
    <header className="header">
      <h1>todos</h1>
      <input
        autoFocus
        className="new-todo"
        onKeyDown={handleKeyDown}
        placeholder="What needs to be done?"
        ref={textRef}
      />
    </header>
  ), [])
}
